/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "a-stock": "/a-stock";
    "a-stock_block-trade": "/a-stock/block-trade";
    "a-stock_industry-board": "/a-stock/industry-board";
    "a-stock_limit-up": "/a-stock/limit-up";
    "a-stock_market-overview": "/a-stock/market-overview";
    "a-stock_stock-hot": "/a-stock/stock-hot";
    "about": "/about";
    "ai": "/ai";
    "ai_analysis": "/ai/analysis";
    "ai_chat": "/ai/chat";
    "ai_market-analysis": "/ai/market-analysis";
    "ai_model": "/ai/model";
    "ai_sector-analysis": "/ai/sector-analysis";
    "business": "/business";
    "business_app-user": "/business/app-user";
    "demo": "/demo";
    "demo_dict": "/demo/dict";
    "demo_openapi-test": "/demo/openapi-test";
    "demo_upload": "/demo/upload";
    "export-record": "/export-record";
    "home": "/home";
    "iframe-page": "/iframe-page/:url";
    "info": "/info";
    "info_news": "/info/news";
    "log": "/log";
    "log_login-log": "/log/login-log";
    "log_online-user": "/log/online-user";
    "log_operation-log": "/log/operation-log";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "manage": "/manage";
    "manage_announcement": "/manage/announcement";
    "manage_config": "/manage/config";
    "manage_dept": "/manage/dept";
    "manage_dict": "/manage/dict";
    "manage_file": "/manage/file";
    "manage_ip-blacklist": "/manage/ip-blacklist";
    "manage_menu": "/manage/menu";
    "manage_role": "/manage/role";
    "manage_user": "/manage/user";
    "merchant-open": "/merchant-open";
    "merchant-open_merchant": "/merchant-open/merchant";
    "merchant-open_openapi-log": "/merchant-open/openapi-log";
    "monitor": "/monitor";
    "scheduler": "/scheduler";
    "scheduler_log": "/scheduler/log";
    "scheduler_task": "/scheduler/task";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "a-stock"
    | "about"
    | "ai"
    | "business"
    | "demo"
    | "export-record"
    | "home"
    | "iframe-page"
    | "info"
    | "log"
    | "login"
    | "manage"
    | "merchant-open"
    | "monitor"
    | "scheduler"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "iframe-page"
    | "login"
    | "a-stock_block-trade"
    | "a-stock_industry-board"
    | "a-stock_limit-up"
    | "a-stock_market-overview"
    | "a-stock_stock-hot"
    | "about"
    | "ai_analysis"
    | "ai_chat"
    | "ai_market-analysis"
    | "ai_model"
    | "ai_sector-analysis"
    | "business_app-user"
    | "demo_dict"
    | "demo_openapi-test"
    | "demo_upload"
    | "export-record"
    | "home"
    | "info_news"
    | "log_login-log"
    | "log_online-user"
    | "log_operation-log"
    | "manage_announcement"
    | "manage_config"
    | "manage_dept"
    | "manage_dict"
    | "manage_file"
    | "manage_ip-blacklist"
    | "manage_menu"
    | "manage_role"
    | "manage_user"
    | "merchant-open_merchant"
    | "merchant-open_openapi-log"
    | "monitor"
    | "scheduler_log"
    | "scheduler_task"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
