/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "a-stock_industry-board": () => import("@/views/a-stock/industry-board/index.vue"),
  "a-stock_limit-up": () => import("@/views/a-stock/limit-up/index.vue"),
  "a-stock_market-overview": () => import("@/views/a-stock/market-overview/index.vue"),
  "a-stock_stock-hot": () => import("@/views/a-stock/stock-hot/index.vue"),
  about: () => import("@/views/about/index.vue"),
  ai_model: () => import("@/views/ai/model/index.vue"),
  "business_app-user": () => import("@/views/business/app-user/index.vue"),
  demo_dict: () => import("@/views/demo/dict/index.vue"),
  "demo_openapi-test": () => import("@/views/demo/openapi-test/index.vue"),
  demo_upload: () => import("@/views/demo/upload/index.vue"),
  "export-record": () => import("@/views/export-record/index.vue"),
  home: () => import("@/views/home/index.vue"),
  info_news: () => import("@/views/info/news/index.vue"),
  "log_login-log": () => import("@/views/log/login-log/index.vue"),
  "log_online-user": () => import("@/views/log/online-user/index.vue"),
  "log_operation-log": () => import("@/views/log/operation-log/index.vue"),
  manage_announcement: () => import("@/views/manage/announcement/index.vue"),
  manage_config: () => import("@/views/manage/config/index.vue"),
  manage_dept: () => import("@/views/manage/dept/index.vue"),
  manage_dict: () => import("@/views/manage/dict/index.vue"),
  manage_file: () => import("@/views/manage/file/index.vue"),
  "manage_ip-blacklist": () => import("@/views/manage/ip-blacklist/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  "merchant-open_merchant": () => import("@/views/merchant-open/merchant/index.vue"),
  "merchant-open_openapi-log": () => import("@/views/merchant-open/openapi-log/index.vue"),
  monitor: () => import("@/views/monitor/index.vue"),
  scheduler_log: () => import("@/views/scheduler/log/index.vue"),
  scheduler_task: () => import("@/views/scheduler/task/index.vue"),
};
