/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      constant: true,
      icon: 'mdi:information-outline',
      order: 9999
    }
  },
  {
    name: 'business',
    path: '/business',
    component: 'layout.base',
    meta: {
      title: 'business',
      i18nKey: 'route.business'
    },
    children: [
      {
        name: 'business_app-user',
        path: '/business/app-user',
        component: 'view.business_app-user',
        meta: {
          title: 'business_app-user',
          i18nKey: 'route.business_app-user'
        }
      }
    ]
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo',
      order: 5,
      icon: 'arcticons:example'
    },
    children: [
      {
        name: 'demo_dict',
        path: '/demo/dict',
        component: 'view.demo_dict',
        meta: {
          title: 'demo_dict',
          i18nKey: 'route.demo_dict',
          icon: 'mdi:book-alphabet'
        }
      },
      {
        name: 'demo_openapi-test',
        path: '/demo/openapi-test',
        component: 'view.demo_openapi-test',
        meta: {
          title: 'demo_openapi-test',
          i18nKey: 'route.demo_openapi-test'
        }
      },
      {
        name: 'demo_upload',
        path: '/demo/upload',
        component: 'view.demo_upload',
        meta: {
          title: 'demo_upload',
          i18nKey: 'route.demo_upload',
          icon: 'mdi:upload'
        }
      }
    ]
  },
  {
    name: 'export-record',
    path: '/export-record',
    component: 'layout.base$view.export-record',
    meta: {
      title: 'export-record',
      i18nKey: 'route.export-record',
      hideInMenu: true,
      keepAlive: true,
      constant: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      icon: 'mdi:file-document-outline',
      order: 3
    },
    children: [
      {
        name: 'log_login-log',
        path: '/log/login-log',
        component: 'view.log_login-log',
        meta: {
          title: 'log_login-log',
          i18nKey: 'route.log_login-log'
        }
      },
      {
        name: 'log_online-user',
        path: '/log/online-user',
        component: 'view.log_online-user',
        meta: {
          title: 'log_online-user',
          i18nKey: 'route.log_online-user'
        }
      },
      {
        name: 'log_operation-log',
        path: '/log/operation-log',
        component: 'view.log_operation-log',
        meta: {
          title: 'log_operation-log',
          i18nKey: 'route.log_operation-log'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage'
    },
    children: [
      {
        name: 'manage_announcement',
        path: '/manage/announcement',
        component: 'view.manage_announcement',
        meta: {
          title: 'manage_announcement',
          i18nKey: 'route.manage_announcement'
        }
      },
      {
        name: 'manage_config',
        path: '/manage/config',
        component: 'view.manage_config',
        meta: {
          title: 'manage_config',
          i18nKey: 'route.manage_config'
        }
      },
      {
        name: 'manage_dept',
        path: '/manage/dept',
        component: 'view.manage_dept',
        meta: {
          title: 'manage_dept',
          i18nKey: 'route.manage_dept'
        }
      },
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict'
        }
      },
      {
        name: 'manage_file',
        path: '/manage/file',
        component: 'view.manage_file',
        meta: {
          title: 'manage_file',
          i18nKey: 'route.manage_file'
        }
      },
      {
        name: 'manage_ip-blacklist',
        path: '/manage/ip-blacklist',
        component: 'view.manage_ip-blacklist',
        meta: {
          title: 'manage_ip-blacklist',
          i18nKey: 'route.manage_ip-blacklist'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user'
        }
      }
    ]
  },
  {
    name: 'merchant-open',
    path: '/merchant-open',
    component: 'layout.base',
    meta: {
      title: 'merchant-open',
      i18nKey: 'route.merchant-open'
    },
    children: [
      {
        name: 'merchant-open_merchant',
        path: '/merchant-open/merchant',
        component: 'view.merchant-open_merchant',
        meta: {
          title: 'merchant-open_merchant',
          i18nKey: 'route.merchant-open_merchant'
        }
      },
      {
        name: 'merchant-open_openapi-log',
        path: '/merchant-open/openapi-log',
        component: 'view.merchant-open_openapi-log',
        meta: {
          title: 'merchant-open_openapi-log',
          i18nKey: 'route.merchant-open_openapi-log'
        }
      }
    ]
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base$view.monitor',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor',
      icon: 'mdi:chart-areaspline-variant',
      order: 4
    }
  },
  {
    name: 'news',
    path: '/news',
    component: 'layout.base$view.news',
    meta: {
      title: 'news',
      i18nKey: 'route.news',
      icon: 'mdi:newspaper-variant',
      order: 5
    }
  },
  {
    name: 'scheduler',
    path: '/scheduler',
    component: 'layout.base',
    meta: {
      title: 'scheduler',
      i18nKey: 'route.scheduler'
    },
    children: [
      {
        name: 'scheduler_log',
        path: '/scheduler/log',
        component: 'view.scheduler_log',
        meta: {
          title: 'scheduler_log',
          i18nKey: 'route.scheduler_log'
        }
      },
      {
        name: 'scheduler_task',
        path: '/scheduler/task',
        component: 'view.scheduler_task',
        meta: {
          title: 'scheduler_task',
          i18nKey: 'route.scheduler_task'
        }
      }
    ]
  }
];
